import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const page = readFileSync(new URL('./VideoDeviceSimulatorPage.vue', import.meta.url), 'utf8');
const composable = readFileSync(new URL('../composables/useDeviceSimulator.ts', import.meta.url), 'utf8');
const deviceSimulatorTypes = readFileSync(new URL('../lib/deviceSimulator.ts', import.meta.url), 'utf8');
const platformRegistration = readFileSync(new URL('../../src-tauri/src/device_simulator/platform_registration.rs', import.meta.url), 'utf8');
const platformReplaceDialog = readFileSync(new URL('../components/DevicePlatformReplaceConfirmDialog.vue', import.meta.url), 'utf8');
const materialResetDialog = readFileSync(new URL('../components/DeviceMaterialResetConfirmDialog.vue', import.meta.url), 'utf8');
const materialMigrationDialog = readFileSync(new URL('../components/DeviceMaterialMigrationConfirmDialog.vue', import.meta.url), 'utf8');
const router = readFileSync(new URL('../router/index.ts', import.meta.url), 'utf8');
const sidebar = readFileSync(new URL('../lib/sidebarNavigation.ts', import.meta.url), 'utf8');
const messages = readFileSync(new URL('../locales/messages.ts', import.meta.url), 'utf8');
const header = page.match(/<header[\s\S]*?<\/header>/)?.[0] ?? '';
const alarmStatsListener = composable.match(/listen<AlarmJobStats>\(DEVICE_SIMULATOR_EVENTS\.alarmStats,[\s\S]*?\n\s*\}\),/)?.[0] ?? '';
const applyStatusAction = composable.match(/function applyStatus\(next: SimulatorStatus\)[\s\S]*?(?=\r?\n\s*function selectAvailableInterface)/)?.[0] ?? '';
const simulatorStopAction = composable.match(/async function stop\(\)[\s\S]*?(?=\r?\n\s*async function recover)/)?.[0] ?? '';
const startAlarmAction = composable.match(/async function startAlarm[\s\S]*?(?=\r?\n\s*async function stopAlarm)/)?.[0] ?? '';
const stopAlarmAction = composable.match(/async function stopAlarm[\s\S]*?(?=\r?\n\s*function addGroup)/)?.[0] ?? '';
const platformAddAction = composable.match(/async function addDevicesToPlatform[\s\S]*?(?=\r?\n\s*async function stop)/)?.[0] ?? '';
const remoteMaterialSyncAction = composable.match(/async function syncRemoteMaterials\(\)[\s\S]*?(?=\r?\n\s*async function addDevicesToPlatform)/)?.[0] ?? '';
const settingsProjection = composable.match(/function settingsFromRequest\(\)[\s\S]*?(?=\r?\n\s*function errorText)/)?.[0] ?? '';

assert.match(router, /path: '\/tools\/video-device-simulator'/);
assert.match(sidebar, /labelKey: 'sidebar\.videoDeviceSimulator'/);
assert.ok(messages.match(/videoDeviceSimulator: 'Virtual Device Simulation'/));
assert.ok(messages.match(/videoDeviceSimulator: '虚拟设备模拟'/));
assert.equal((messages.match(/paperTodo: 'PaperTodo'/g) ?? []).length, 1, 'the English sidebar name must remain PaperTodo');
assert.equal((messages.match(/title: 'PaperTodo'/g) ?? []).length, 1, 'the English PaperTodo title must remain unchanged');
assert.ok(messages.includes("paperTodo: 'PaperTodo 便签'"));
assert.ok(messages.includes("title: 'PaperTodo 便签'"));
assert.ok(messages.includes("settingsTitle: 'PaperTodo 便签设置'"));
assert.ok(messages.includes("confirmImport: '导入会替换当前 PaperTodo 便签数据，是否继续？'"));
assert.ok(messages.includes("settingsTitle: 'PaperTodo Settings'"));
assert.ok(messages.includes("confirmImport: 'Importing replaces the current PaperTodo data. Continue?'"));
assert.ok(messages.includes("title: '虚拟设备模拟'"));
assert.ok(messages.includes("title: '发图配置'"));
for (const legacyLabel of ['服务器配置', '虚拟设备起始 IP', '虚拟设备数量', '设备类型', '发送图片规格', '发送图片间隔（毫秒）', '预设发包数', '告警类型', '数据统计']) {
  assert.ok(messages.includes(legacyLabel), `missing familiar label: ${legacyLabel}`);
}

assert.match(page, /min-h-11/, 'primary controls should meet the 44px target');
assert.match(page, /focus-visible:ring-2/, 'keyboard focus must remain visible');
assert.match(page, /prefers-reduced-motion: reduce/, 'reduced motion must be respected');
assert.match(page, /configSection = ref<'server' \| 'network' \| 'media' \| 'devices'>\('server'\)/, 'server must be the default configuration section');
assert.match(page, /<HintTip/, 'dense configuration guidance must remain keyboard-accessible on demand');
assert.match(page, /min-h-\[68px\][^>]*border-t/, 'launch controls must stay in the fixed bottom action bar');
assert.doesNotMatch(page, /xl:sticky xl:top-5/, 'the duplicated launch summary card must be removed');
assert.match(page, /:disabled="simulator\.topologyLocked\.value"/, 'topology fields must lock while active');
assert.match(page, /simulator\.recoverySessionId\.value/, 'residual sessions must be presented before normal work');
assert.match(page, /const recoveryRequired = computed/, 'recovery must be distinct from a running session');
assert.match(header, /v-if="stoppable"/, 'runtime stop must remain available in the page header on every tab');
assert.match(header, /@click="simulator\.stop"/, 'the persistent header stop must invoke the simulator stop action');
assert.match(header, /busyAction\.value === 'stop'[\s\S]*<Power[\s\S]*deviceSimulator\.actions\.stop/, 'the header stop must use a recognizable power icon with its loading state and label');
assert.equal((page.match(/<Power v-else/g) ?? []).length, 2, 'both simulator shutdown actions must use the power icon');
assert.match(page, /deviceSimulator\.actions\.recovering/, 'recovery must expose visible in-progress feedback');
assert.match(page, /simulator\.runPreflight/, 'structured preflight must be available');
assert.match(page, /address_assessments/, 'address checks must expose per-address evidence');
assert.match(page, /addressEvidenceText/, 'address evidence must identify local or neighboring owners');
assert.ok(messages.includes("addressConflicts: '地址占用检查'"));
assert.ok(messages.includes("inconclusive: '暂时无法确认以下地址是否空闲：{addresses}。这不表示地址已经被占用。'"));
assert.match(page, /simulator\.alarmStats\.value/, 'alarm statistics must be visible');
assert.match(deviceSimulatorTypes, /interface AlarmJobStats[\s\S]*last_http_status: number \| null;/, 'alarm statistics must carry the latest HTTP response status');
assert.match(page, /deviceSimulator\.alarms\.lastHttpStatus[\s\S]*simulator\.alarmStats\.value\?\.last_http_status \?\? '—'/, 'the latest HTTP status must use a dash when no response was received');
assert.ok(messages.includes("lastHttpStatus: 'Last HTTP status'"));
assert.ok(messages.includes("lastHttpStatus: '最近 HTTP 状态'"));
assert.ok(messages.includes("unverified: 'Responded, not verified'"));
assert.ok(messages.includes("unverifiedHint: 'An HTTP response was received, but whether UMS processed the picture successfully has not been verified.'"));
assert.ok(messages.includes("unverified: '已响应未验证数'"));
assert.ok(messages.includes("unverifiedHint: '已收到 HTTP 响应，但尚未验证 UMS 是否已正确处理图片。'"));
assert.match(page, /simulator\.alarmTypes\.value/, 'alarm names must come from the prepared device files');
assert.match(page, /requiredFileLabel/, 'internal file identifiers must use familiar display labels');
assert.match(page, /id="asset-details"[\s\S]*assetTone !== 'ready'[\s\S]*@click="simulator\.syncRemoteMaterials"/, 'missing files must expose server sync at the point of failure');
assert.match(page, /deviceSimulator\.assets\.syncHint/, 'the missing-file panel must explain the first-use sync action');
assert.match(remoteMaterialSyncAction, /refreshMediaThemes\(\);[\s\S]*refreshAssets\(\);/, 'server sync must automatically refresh required-file readiness');
assert.match(messages, /syncHint: 'On first use, sync the prepared live video and alarm pictures from the upgrade server\.'/);
assert.match(messages, /syncHint: '首次使用请先从升级服务器同步实况视频和告警图片。'/);
assert.doesNotMatch(messages, /告警类型 ID/, 'internal alarm IDs must not be shown to users');
assert.doesNotMatch(page, /<option value="normal">/, 'picture sizes must keep the legacy three-choice UI');
assert.doesNotMatch(page, /value="vms"|>VMS</i, 'the simulator must expose UMS only');
assert.match(composable, /STRUCTURED_PROFILE_ID = 'ipc-structured'/, 'the structured camera must be the configured profile');
for (const [name, source] of [['page', page], ['composable', composable], ['types', deviceSimulatorTypes], ['messages', messages]]) {
  assert.doesNotMatch(
    source,
    /ipc-custom|ipc-smart|ipc-face-access|nvr-common|nvr-vehicle/,
    `only the structured camera is simulated, but ${name} still names another profile`,
  );
}
assert.match(page, /send_count: continuousAlarm\.value \? null/, 'continuous alarm mode must cross the API as null, never a magic zero');
assert.match(page, /const continuousAlarm = ref\(true\)/, 'continuous picture sending must be selected by default');
assert.doesNotMatch(page, /\bSquare\b/, 'the stop-sending state must not look like a missing-glyph square');
assert.match(page, /<XCircle v-else-if="alarmSending"/, 'the stop-sending state must use an explicit non-power stop icon');
assert.match(composable, /isDeviceSimulatorRuntimeActive\(next\.state\)[\s\S]*preflight\.value = null/, 'an active runtime must retire its startup-only preflight report');
assert.match(page, /<fieldset[\s\S]*:disabled="alarmConfigurationLocked"[\s\S]*<legend/, 'all picture settings must lock as one accessible group while sending');
assert.match(page, /const alarmConfigurationLocked = computed\([\s\S]*alarmSending\.value[\s\S]*alarmStartPending\.value/, 'the picture settings must lock before and throughout a continuous send');
assert.match(messages, /configurationLocked: '正在发送图片，停止发送后才能修改配置。'/, 'the locked picture settings must explain how to edit them again');
assert.match(page, /v-model="selectedAlarmTypeId"[^>]*:disabled="availableAlarmTypes\.length === 0 \|\| alarm\.mode !== 'configured'"/, 'only configured dispatch may pin one explicit alarm type');
assert.match(page, /<option value="configured" :disabled="availableAlarmTypes\.length === 0"/, 'configured dispatch must be selectable whenever alarm types are available');
assert.match(page, /watch\(\(\) => alarm\.mode,[\s\S]*mode === 'configured'[\s\S]*availableAlarmTypes\.value\[0\]\?\.id/, 'configured dispatch must automatically select an available alarm type');
assert.match(page, /!alarmTypeId && alarm\.mode === 'configured'/, 'clearing the alarm type must leave configured mode, which requires exactly one type');
assert.match(page, /downloadJson\('device-simulator-logs\.json'/, 'logs must be exportable');

assert.match(composable, /DEVICE_SIMULATOR_EVENTS\.status/);
assert.match(composable, /DEVICE_SIMULATOR_EVENTS\.cleanupProgress/);
assert.match(composable, /hasBlockingPreflightFailure/);
assert.match(composable, /payload\.state === 'ready'[\s\S]*refreshAlarmTypes\(\)/, 'alarm names must refresh when required files finish preparing');
assert.match(composable, /status\.state === 'ready' \|\| status\.state === 'update_available'/, 'installed alarm names must remain available when a newer file set exists');
assert.match(composable, /last_platform_servers[\s\S]*\[\{ id: newId\('server'\), host: '', port: 80 \}\]/, 'saved servers must be restored with a visible empty fallback');
assert.match(simulatorStopAction, /if \(stopped === null\) return;[\s\S]*activeAlarmJobId\.value = null;[\s\S]*deviceSimulatorApi\.getStatus\(\)/, 'a successful simulator stop must clear the active alarm before refreshing status');
assert.match(composable, /last_alarm_receiver_port: 22_815/, 'the observed UMS receiver port 22815 must be the fallback default');
assert.match(composable, /alarm_receiver_port: settings\.last_alarm_receiver_port/, 'saved receiver port must enter the runtime request');
assert.match(composable, /last_alarm_receiver_port: request\.platform\.alarm_receiver_port/, 'receiver port must persist with app settings');
assert.match(page, /v-model\.number="simulator\.request\.platform\.alarm_receiver_port"[\s\S]*type="number"[\s\S]*min="1"[\s\S]*max="65535"/, 'advanced settings must expose a bounded picture receiver port input');
assert.match(messages, /alarmReceiverPort:\s*'Picture \/ alarm receiver port'/, 'English copy must name the independent receiver port');
assert.match(messages, /alarmReceiverPort:\s*'图片\/告警接收端口'/, 'Chinese copy must name the independent receiver port');
assert.match(page, /deviceSimulator\.fields\.alarmReceiverHint/, 'the complete receiver URL must explain that it pins the destination');
assert.match(page, /deviceSimulator\.fields\.alarmReceiverPortHint/, 'the receiver port must explain that it is only a pre-subscription fallback');
assert.match(messages, /alarmReceiverPortHint: 'Fallback used only until the platform subscribes[^']*Default 22815\.'/, 'English receiver port copy must present the port as a fallback and name 22815');
assert.match(messages, /alarmReceiverPortHint: '仅在尚未收到平台订阅时作为兜底使用[^']*默认 22815。'/, 'Chinese receiver port copy must present the port as a fallback and name 22815');

// The advanced receiver URL and the loose-material server URL are unrelated
// settings that were previously side by side and easy to confuse.
assert.match(page, /deviceSimulator\.configuration\.advanced[\s\S]*deviceSimulator\.fields\.alarmReceiver\b[\s\S]*deviceSimulator\.fields\.assetServer/, 'both advanced URLs must live inside the collapsed advanced block');
assert.match(messages, /assetServer: 'Material server URL \(advanced\)'/, 'English asset source copy must name the material server');
assert.match(messages, /assetServer: '素材服务器地址（高级）'/, 'Chinese asset source copy must name the material server');
assert.match(messages, /assetServerHint: '已预处理虚拟设备视频与告警图片的同步来源。/, 'the asset source hint must explain the prepared-material source');
assert.match(page, /deviceSimulator\.configuration\.serversHint/, 'the server list must explain that alarms are distributed, not broadcast');
assert.match(messages, /serversHint: '这里的服务器是告警投递目标[^']*告警按顺序分摊/, 'Chinese server copy must state that alarm delivery is distributed');
assert.match(page, /v-model="simulator\.settings\.value\.platform_username"/, 'the current server panel must expose the UMS username');
assert.match(page, /v-model="simulator\.settings\.value\.platform_password"/, 'the current server panel must expose the UMS password');
assert.match(page, /platformPasswordVisible \? 'text' : 'password'/, 'the UMS password must support explicit reveal and conceal');
assert.match(page, /v-model="simulator\.settings\.value\.platform_auto_add_devices"/, 'the current server panel must expose automatic registration');
assert.match(composable, /platform_auto_add_devices: true/, 'automatic registration must be checked by default');
assert.match(page, /v-model="simulator\.settings\.value\.platform_replace_existing_devices"/, 'the server panel must expose the replace-existing preference');
assert.match(composable, /platform_replace_existing_devices: false/, 'destructive replacement must be unchecked by default');
assert.match(settingsProjection, /\.\.\.settings\.value/, 'the automatic-registration preference must survive the settings projection');
assert.match(composable, /deviceSimulatorApi\.saveSettings\(next\)/, 'the projected preference must be written through the persistent settings command');
assert.match(page, /platformAutoAddNeedsConfig/, 'automatic registration must surface incomplete configuration before start');
assert.match(page, /simulator\.platformAddReport\.value/, 'registration outcomes must be visible on the runtime tab');
assert.match(page, /simulator\.addDevicesToPlatform/, 'partial or failed registration must be retryable without restarting devices');
assert.match(page, /action === 'add-to-platform'[\s\S]*activeTab\.value = 'runtime'/, 'registration progress and results must move into view on the runtime tab');
assert.match(platformAddAction, /preview\.value\?\.devices[\s\S]*address: device\.ip[\s\S]*port: request\.device_http_port/, 'registration must use every previewed device and its active HTTP port');
assert.match(platformAddAction, /run\('add-to-platform'[\s\S]*deviceSimulatorApi\.addDevicesToPlatform\(devices, replaceExisting\)/, 'platform registration must have a busy/error boundary separate from start');
assert.match(composable, /applyStatus\(result\);[\s\S]*platform_auto_add_devices[\s\S]*addDevicesToPlatform\(replaceExisting\)/, 'automatic registration must run only after the simulator status is applied');
assert.match(composable, /failedAt === 'add'[\s\S]*platformReplacePromptOpen\.value = true/, 'an automatic add failure must open the replacement confirmation only after an add-stage failure');
assert.match(composable, /confirmPlatformReplaceRetry[\s\S]*addDevicesToPlatform\(true\)/, 'confirming replacement must force query-delete-add mode');
assert.match(platformReplaceDialog, /role="alertdialog"[\s\S]*aria-modal="true"/, 'the retry question must use a centered application modal');
assert.match(platformReplaceDialog, /cancelButton\.value\?\.focus\(\)/, 'the safe cancel action must receive initial focus');
assert.match(platformReplaceDialog, /currentWindow\.show\(\)[\s\S]*currentWindow\.unminimize\(\)[\s\S]*currentWindow\.setFocus\(\)/, 'the main window must be restored before asking the user');
assert.match(platformReplaceDialog, /@keydown\.tab\.stop="keepFocusInside"/, 'keyboard focus must stay inside the confirmation dialog');
assert.match(platformRegistration, /PLATFORM_QUERY_DEVICE_PATH[\s\S]*\/xapi\/uap\/v1\/resource\/query/, 'replacement must use the platform resource query endpoint');
assert.match(platformRegistration, /RESOURCE_QUERY_PAGE_SIZE: u32 = 200[\s\S]*checked_add\(1\)/, 'resource queries must continue page by page beyond 200 results');
assert.match(platformRegistration, /query_existing_device_ids[\s\S]*\.post\(url\.clone\(\)\)[\s\S]*\.header\("authorization", token\)/, 'device queries must be authenticated POST requests');
assert.match(platformRegistration, /delete_existing_devices[\s\S]*\.post\(url\)[\s\S]*\.header\("authorization", token\)/, 'device deletion must be an authenticated POST request');
assert.match(platformRegistration, /HTTP request: POST \{url_for_log\}/, 'the RSA public-key POST request URL must reach the run log');
assert.match(platformRegistration, /let response = client\s*\.post\(url\)/, 'the UMS RSA public-key endpoint must be called with POST');
assert.doesNotMatch(platformRegistration, /let response = client\s*\.get\(url\)/, 'the UMS RSA public-key endpoint rejects GET');
assert.match(platformRegistration, /HTTP response: \{method\} \{url\}[\s\S]*body=\{\}/, 'HTTP status and response bodies must reach the run log');
assert.match(platformRegistration, /authorization=<redacted>/, 'authorization values must be redacted in diagnostics');
assert.match(page, /whitespace-pre-wrap break-all[^>]*>\{\{ entry\.message \}\}/, 'long JSON response logs must wrap instead of being visually truncated');
assert.match(page, /downloadJson\('device-simulator-logs\.json'[\s\S]*whitespace-nowrap[\s\S]*common\.export/, 'the log export label must stay on one line');
assert.match(page, /function formatLogTimestamp\(timestamp: string\)[\s\S]*getFullYear\(\)[\s\S]*getHours\(\)[\s\S]*getMilliseconds\(\)/, 'log timestamps must be formatted in the current computer local time');
assert.match(page, /lg:grid-cols-\[190px_76px_190px_minmax\(0,1fr\)\]/, 'the local timestamp column must have a fixed width');
assert.match(page, /w-\[190px\] whitespace-nowrap[\s\S]*formatLogTimestamp\(entry\.timestamp\)/, 'the complete millisecond timestamp must remain on one line');

// A learned subscription is the difference between alarms reaching the platform
// and silently going to a port nobody listens on, so it must be visible.
assert.match(composable, /DEVICE_SIMULATOR_EVENTS\.alarmSubscription/, 'the composable must subscribe to alarm subscription telemetry');
assert.match(composable, /const alarmSubscription = ref<AlarmSubscription \| null>\(null\)/, 'learned subscription state must be exposed to the page');
assert.match(simulatorStopAction, /alarmSubscription\.value = null/, 'stopping must clear the learned subscription with the session');
assert.match(page, /deviceSimulator\.subscription\.waitingTitle/, 'the page must call out that no platform subscription has arrived');
assert.match(page, /deviceSimulator\.subscription\.expiredTitle/, 'the page must call out an expired platform subscription');
assert.match(page, /subscription\.destinations\.join/, 'the effective alarm destination must be rendered');
assert.match(messages, /waitingDescription: '平台通常在添加设备时、或设备离线再上线后才下发订阅。/, 'the waiting copy must explain when a platform normally subscribes');

// The real failure code was previously dropped, leaving only one generic
// sentence for every distinct cause.
assert.match(page, /alarmError\.code/, 'the raw alarm error code must always be rendered');
assert.match(page, /alarmError\.details/, 'the sanitized failure cause must be rendered');
assert.match(composable, /component: 'alarm:dispatch'/, 'alarm failures must reach the run log');
assert.match(composable, /const signature = `\$\{stats\.job_id\}\|\$\{error\.code\}\|\$\{error\.details \?\? ''\}`/, 'repeated identical alarm failures must not flood the run log');
assert.match(composable, /sharedDeviceSimulator/, 'page drafts and asset state must survive route changes');
assert.match(composable, /if \(stopped === null\) return;/, 'a failed stop must preserve its error instead of refreshing it away');
assert.match(composable, /if \(!recovered\) return;/, 'a failed recovery must preserve its error instead of refreshing it away');
assert.match(composable, /const activeAlarmJobId = ref<string \| null>\(null\)/, 'the API-returned alarm job id must have an explicit active-state source');
assert.match(composable, /const alarmStartPending = ref\(false\)/, 'an in-flight alarm start must reject duplicate starts before the API returns');
assert.match(composable, /const alarmStopPending = ref\(false\)/, 'an alarm stop must latch immediately to prevent duplicate requests');
assert.match(applyStatusAction, /shouldReleaseActiveAlarmJob\(next, alarmStartPending\.value\)[\s\S]*activeAlarmJobId\.value = null/, 'backend status with no alarm jobs must release a stale frontend job id without racing an in-flight start');
assert.match(composable, /DEVICE_SIMULATOR_EVENTS\.status[\s\S]*applyStatus\(payload\)/, 'live backend status must reconcile alarm button state');
assert.match(composable, /statusResult\.status === 'fulfilled'\) applyStatus\(statusResult\.value\)/, 'initial and manual status refreshes must reconcile alarm button state after a Worker restart');
assert.match(startAlarmAction, /if \(activeAlarmJobId\.value \|\| alarmStartPending\.value \|\| alarmStopPending\.value\) return;/, 'active, starting, or stopping alarm work must block another start');
assert.match(startAlarmAction, /const jobId = await run\('start-alarm',[\s\S]*deviceSimulatorApi\.startAlarm\(alarm\)[\s\S]*activeAlarmJobId\.value = jobId/, 'start must save the job id returned by the API');
assert.match(startAlarmAction, /activeAlarmJobId\.value = jobId;[\s\S]*alarmStats\.value\?\.job_id === jobId[\s\S]*alarmStats\.value\.state === 'completed'[\s\S]*alarmStats\.value\.state === 'failed'[\s\S]*activeAlarmJobId\.value = null/, 'a terminal event received before the start response must not restore a finished job as active');
assert.match(stopAlarmAction, /const jobId = activeAlarmJobId\.value;[\s\S]*if \(!jobId \|\| alarmStopPending\.value\) return;/, 'stop must use the active job id and reject repeat requests');
assert.match(stopAlarmAction, /alarmStopPending\.value = true;[\s\S]*deviceSimulatorApi\.stopAlarm\(jobId\)/, 'stop must latch before invoking the API with the active id');
assert.match(stopAlarmAction, /if \(stopped && activeAlarmJobId\.value === jobId\) activeAlarmJobId\.value = null;/, 'a successful stop must clear only the stopped active job');
assert.match(stopAlarmAction, /finally[\s\S]*alarmStopPending\.value = false/, 'the stop latch must be released after the request settles');
assert.doesNotMatch(stopAlarmAction, /alarmStats\.value = null/, 'stopping must retain the final alarm statistics');
assert.match(alarmStatsListener, /alarmStats\.value = payload/, 'alarm events must continue updating visible statistics');
assert.match(alarmStatsListener, /activeAlarmJobId\.value === payload\.job_id/, 'terminal stats must only clear their matching active job');
assert.match(alarmStatsListener, /payload\.state === 'completed'/, 'completed alarm stats must clear active state');
assert.match(alarmStatsListener, /payload\.state === 'failed'/, 'failed alarm stats must clear active state');
assert.match(alarmStatsListener, /activeAlarmJobId\.value = null/, 'terminal stats must release the active job without discarding stats');
assert.match(page, /const alarmSending = computed\(\(\) => simulator\.activeAlarmJobId\.value !== null\)/, 'alarm sending must expose one source of truth for the toggle state');
assert.match(page, /async function toggleAlarmSending\(\)[\s\S]*if \(alarmSending\.value\)[\s\S]*simulator\.stopAlarm\(\)[\s\S]*startAlarm\(\)/, 'the alarm control must toggle between starting and stopping one job');
assert.match(page, /:aria-pressed="alarmSending"[\s\S]*@click="toggleAlarmSending"/, 'send and stop must share one accessible toggle button');
assert.equal((page.match(/@click="toggleAlarmSending"/g) ?? []).length, 1, 'the send/stop toggle must be rendered once');
assert.match(page, /busyAction\.value === 'sync-remote-materials'[\s\S]*animate-spin/, 'server material sync must expose visible progress');
assert.match(page, /runtimeActive \|\| simulator\.busyAction\.value !== null[^>]*@click="simulator\.syncRemoteMaterials"/, 'server material sync must prevent duplicate or unsafe activation');
assert.match(page, /deviceSimulator\.mediaThemes\.resetRemote/, 'server-managed materials must expose a clear-and-resync action');
assert.match(page, /openDirectory\(\)/, 'the material root must be selectable from the simulator page');
assert.match(page, /deviceSimulator\.mediaThemes\.changeStorageDirectory/, 'directory selection must use a clearly labelled action');
assert.doesNotMatch(page, /DirectoryPathInput/, 'the material directory must not be shown twice through a second path input');
assert.match(composable, /localMaterialsPath\.value = await deviceSimulatorApi\.getLocalMaterialsPath\(\)/, 'saving a material directory must refresh the effective path');
assert.match(deviceSimulatorTypes, /local_materials_directory: string \| null;/, 'the custom material directory must cross the typed settings boundary');
assert.match(page, /localMaterialsDirectoryChanged\.value[\s\S]*materialMigrationPromptOpen\.value = true/, 'saving a changed directory must open the migration choice');
assert.match(page, /requestSettingsAction\('start'\)/, 'starting with an unsaved directory change must use the same migration choice');
assert.match(composable, /deviceSimulatorApi\.migrateLocalMaterials\(next\)/, 'confirmed migration must use the native verified-copy command');
assert.match(deviceSimulatorTypes, /migrateLocalMaterials: 'device_simulator_migrate_local_materials'/, 'the migration command must cross the typed API boundary');
assert.match(materialMigrationDialog, /role="alertdialog"[\s\S]*aria-modal="true"/, 'material migration must use an application confirmation dialog');
assert.match(materialMigrationDialog, /cancelButton\.value\?\.focus\(\)/, 'the safe cancel action must receive initial focus');
assert.match(materialMigrationDialog, /getCurrentWindow\(\)[\s\S]*window\.show\(\)[\s\S]*window\.unminimize\(\)[\s\S]*window\.setFocus\(\)/, 'the main window must be restored before asking about material migration');
assert.match(materialMigrationDialog, /@keydown\.tab\.stop="keepFocusInside"/, 'keyboard focus must stay inside the migration dialog');
assert.match(materialMigrationDialog, /emit\('switchOnly'\)[\s\S]*emit\('migrate'\)/, 'the dialog must offer switch-only and verified migration choices');
assert.match(messages, /localHint: 'Server videos are preprocessed once by the publisher and play immediately after clients download them\.'/);
assert.match(messages, /localHint: '服务器视频由素材发布者一次性预处理，客户端下载后直接播放'/);
assert.doesNotMatch(messages, /localHint: '[^']*FFmpeg/, 'the server-material explanation must not mention FFmpeg');
assert.match(page, /DeviceMaterialResetConfirmDialog/, 'clearing server materials must require an application confirmation dialog');
assert.match(deviceSimulatorTypes, /resetAndSyncRemoteMaterials: 'device_simulator_reset_and_sync_remote_materials'/, 'the reset command must cross the typed API boundary');
assert.match(materialResetDialog, /role="alertdialog"[\s\S]*aria-modal="true"/, 'the material reset warning must be an application modal');
assert.match(materialResetDialog, /cancelButton\.value\?\.focus\(\)/, 'the safe cancel action must receive initial focus');
assert.match(materialResetDialog, /getCurrentWindow\(\)[\s\S]*window\.show\(\)[\s\S]*window\.unminimize\(\)[\s\S]*window\.setFocus\(\)/, 'the main window must be restored before material reset confirmation');
assert.match(materialResetDialog, /@keydown\.tab\.stop="keepFocusInside"/, 'keyboard focus must stay inside the material reset dialog');
assert.match(page, /simulator\.request\.device_ips/, 'non-contiguous device addresses must cross the API boundary');
assert.match(page, /openPingScanner/, 'the network ping scanner must be reachable from device IP configuration');
assert.match(page, /simulator\.selectedInterface\.value/, 'the selected adapter must be visible without opening advanced settings');
assert.match(page, /interfaceSelectionDescription/, 'automatic adapter selection must explain its subnet decision');
assert.match(composable, /recommendSimulatorInterface/, 'adapter selection must use target-IP subnet matching');
assert.doesNotMatch(page, /simulator\.blockingPreflight\.value" @click="simulator\.start"/, 'start must run its own preflight instead of silently remaining disabled');
assert.doesNotMatch(composable, /access_token|worker_process_id/i);
assert.doesNotMatch(composable, /request\.[a-zA-Z0-9_]*password|password.*InitializeSessionPayload/i, 'platform credentials must not enter the Worker start request');

console.log('VideoDeviceSimulatorPage contract tests PASSED');
